# Generated by Django 4.2.4 on 2023-08-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='pr_of_sub_user-user',
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(
                check=models.Q(('author', models.F('user')), _negated=True),
                name='pr_of_sub_user_user',
            ),
        ),
    ]
